### ISSUE TITLE
Refactor code for running from custom initial state

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/modelator#193]
Currently, the logic for the feature of guided traces is [in the check function](https://github.com/informalsystems/modelator/blob/22466a2c6695e5847380db96acb75daf8b9af31c/modelator/check.py#L95). This is very likely not the right place for it, since it is available for Apalache, but not for TLC. A better place might be on the top (shell) level. (still to be discussed)

**Comment by rnbguy** [comment]
I think there should be a developer API for Modelator. Because we will still use it for writing CI for AtomKraft E2E. The modelator shell should be a convenient script-friendly version.

Ideally, we should use,
- A base Checker class, and
- ApalacheChecker and TLCChecker to extend it.

Probably this is what you had in mind (until I merged my code inside `check_apalache`). Anyway, let me record the idea here.

From a python shell,
```python
from modelator.shell import *
model = Model.load_model(...)
model.check(..., checker="apalache")
```

Inside `shell.py`
```python
from .checker import ApalacheChecker, TlcChecker

class Model:
   def load_model(...):
     ...

   def check(..., checker=None):
     if checker is None:
       checker = "apalache"
     match checker:
       case "apalache":
         mc = ApalacheChecker()
       case "tlc":
         mc = TlcChecker()
     return mc.check(self)
```

Inside `checker.py`
```python
class Checker():
  def check(...):
     ...
     # prepare the tla files and config for checkers
     return self._check(...)

  @abstractmethod
  def _check(...):
    pass

class ApalacheChecker(Checker):
  def _check(...):
    # use modelator-py here for apalache

class TlcChecker(Checker):
  def _check(...):
    # use modelator-py here for tlc
```

- The code for the custom initial state should go in the `Checker.check`. Because it is common for both checkers.
- `ApalacheChecker` and `TLCChecker` should just implement (probably using `modelator-py` directly).
  - How to check a TLA main file with a set of TLA files and a TLA config.
  - How to parse and return the generated TLA traces, output, and error.

**Comment by rnbguy** [comment]
Also, in my opinion `python -i modelator_shell.py` is not a good idea for packaging. We should go for something `from modelator.shell import *`. Because then people can just do `pip install modelator` and use it as a python module directly.
