### ISSUE TITLE
Use tla_python parser

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/modelator#200]
At the moment we are using the Sany parser, by calling Apalache's `parse` command. 
This works, however, we need to extract information from the input and it is slow. 
Instead, we shuld use this [Python parses for TLA+](https://github.com/tlaplus/tla_python/branches). 
On top of giving us info on whether a file parses or not, it will also give information about variables, constants, files that the main tla file extends (addressing the issue #182 ) etc.

**Comment by ivan-gavran** [comment]
After getting deeper into the task, I encountered several problems:
 - the parser will only parse contents of a single file out of the box. (It will provide information about which are the files extendees and instancees, though.) We would still need to handle the logic of putting all those files together and, based on the error message, figuring out the location of the error in each individual file. We get all of these for free in Sany
 - error messages seem to be less informative than the ones we get from Sany

Based on these problems, I suggest to give up on this issue (unless a more convincing reason for using this parser exists)

**Comment by ivan-gavran** [comment]
@danwt , would like to hear your take on this (in case I overlooked something in the `tla_python` parser)

**Comment by danwt** [comment]
> the parser will only parse contents of a single file out of the box. (

Correct, it's a parser not an interpreter.

> error messages seem to be less informative than the ones we get from Sany

That could well be.

> Based on these problems, I suggest to give up on this issue

I don't know to be honest. You might find SANY ok. You could try to extract the sany code from the rest of the tlaplus/ code [(link)](https://github.com/tlaplus/tlaplus/tree/master/tlatools/org.lamport.tlatools/src/tla2sany).

I experimented with the [CLI](https://github.com/tlaplus/tlaplus/blob/6ee6e9f1fe4b6879b7e9cdc4b3e6db687e03a03c/tlatools/org.lamport.tlatools/src/tla2sany/explorer/Explorer.java#L389) and got sany to dump json. _However_ @konnov warned me that they spent *years* in Apalache to properly use SANY's output. That's why I opted for tla_python.

> We would still need to handle the logic of putting all those files together and, based on the error message, figuring out the location of the error in each individual file 

Yeah that sucks, but AFAIK when it comes to TLA+ code manipulation, there are no easy answers.

A while ago I made an issue discussing the parsing options, and @konnov and @shonfeder  participated. I cannot find it for the life of me! Does anybody have any clue (@andrey-kuprianov)?

**Comment by konnov** [comment]
> At the moment we are using the Sany parser, by calling Apalache's parse command.
> This works, however, we need to extract information from the input and it is slow.

Do you know the source of the slowdown? Is it just bootstrapping JVM and Scala? If so, parsing may be the first command that we should integrate in the server mode. /cc @shonfeder

**Comment by ivan-gavran** [comment]
> Is it just bootstrapping JVM and Scala?

Yes, exactly that.
