### ISSUE TITLE
Should we keep dead/unused code in comments?

### ISSUE THREAD

**Issue by danwt** [informalsystems/modelator#72]
Currently there are instances of chunks of commented out code interleaved with live code. For instance
```
        // TODO: disabling cache for now; see https://github.com/informalsystems/modelator/issues/46
        // load cache and check if the result is cached
        // let mut cache = TlaTraceCache::new(options)?;
        // let cache_key = TlaTraceCache::key(&tla_file, &tla_config_file)?;
        // if let Some(value) = cache.get(&cache_key)? {
        //     return Ok(value);
        // }
```
in `src/../apalache/mod.rs`.

Similarly, many docstrings are marked with `ignore`.

Leaving commented out code is considered by some to be a smell. There is a philosophy that the only things in `main` should be 'live' docs and code. Following such guidelines implies it's better to simply delete non-running code. The rationality is that any commented out code will become irrelevant so quickly as to make it useless, unless the turnaround to bring it back to life is extremely short.

I'm inclined to agree with this kind of philosophy, but code style is a very subjective issue so it should be agreed and discussed as a team.

**Comment by andrey-kuprianov** [comment]
This particular code will be re-enabled as soon as we fix the cache to work properly again. Similarly with the now-disabled doctests.

What I am strictly against, is being overly puristic about the code style. E.g., in the previous iterations some code was deleted only because the "unused_code" attribute was set for cargo. This leads to very unpleasant situations when some code that has been written, but not yet fully integrated, gets deleted only because of such puristic considerations. This is especially valid for actively developed projects with not-yet-stable code bases. 

At some point we might do a joint code review, and agree on the style; but this is not critical for now, I believe.

**Comment by danwt** [comment]
Ok that's fine. I also don't agree with being puristic - pragmatism always wins.

**Comment by rnbguy** [comment]
I think we should not have a crate level `#![allow(unused_imports, dead_code)]` - they should be used locally for small pieces for code such as these.

**Comment by danwt** [comment]
Closed as resolved.
