### ISSUE TITLE
Windows test build fails

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#82]
See this [test run](https://github.com/informalsystems/modelator/runs/3477222642):
 - TLC is not found for some reason
 - TMate session never finishes (I think it is disabled for macOS and Ubuntu builds)

**Comment by rnbguy** [comment]
Ah. I didn't see this issue at all. I pushed fix already.

- TLC was not found because the path separator character on Windows is `;` not `:`. See the fix https://github.com/informalsystems/modelator/commit/b9144085ee7a8d5df121378cb7a65d14cc4fb428.
- TMate is supposed to keep on running (unless timedout) until you ssh into the session (and debug the failures) and closes it. See,
  - [Why does TMate write SSH string to log every 5 minutes?](https://github.com/mxschmitt/action-tmate/issues/1)
  - [TMate timeout](https://github.com/mxschmitt/action-tmate#timeout)

**Comment by andrey-kuprianov** [comment]
@rnbguy this is closed via https://github.com/informalsystems/modelator/commit/b9144085ee7a8d5df121378cb7a65d14cc4fb428, right?

In that case we should close the issue.

**Comment by rnbguy** [comment]
@andrey-kuprianov I wanted your response for the TMate config. Should we add a hard timeout for it - in case, any future build fails?

**Comment by andrey-kuprianov** [comment]
yes, let's add a hard timeout, say of 3 minutes. Thanks!
